sudo: false
language: node_js
node_js:
  - stable
install:
  - npm install
notifications:
  email: false
services:
  - postgresql
before_script:
  - psql -c 'create database bcaster_test;' -U postgres
  - 'npm run createTables'
script:
  - 'npm run test'
after_success:
  - 'npm run coverage'
